config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'reports/index', to: 'reports#index'
  get 'reports/report_by_category', to: 'reports#report_by_category'
  get 'reports/report_by_dates', to: 'reports#report_by_dates'
  get 'main/index'
  root 'main#index'
  resources :operations
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
# FrozenStringLiteral
class Category < ApplicationRecord
  has_many :operations, dependent: :destroy
  belongs_to :user

  enum types: { expense: 1, income: 2 }

  validates :name, presence: true, uniqueness: { scope: :user_id, message: 'This category has already exist.' }
  validates :description, presence: true
  validates :user_id, presence: true
  validates :types, inclusion: { in: types.keys }

  paginates_per 4

  def self.categories_of_user(user = 0)
    Category.where(user_id: user).order(:name)
  end

  def self.categories_types
    Category.types.keys.map { |type| [type.humanize, type] }
  end
end

app/models/operation.rb
# class Operation
class Operation < ApplicationRecord
  belongs_to :category
  belongs_to :user

  enum types: { income: 1, expense: 2 }

  validates :user_id, presence: true
  validates :category_id, presence: true
  validates :amount, numericality: true
  validates :odate, presence: true
  validates :description, presence: true
  validates :types, inclusion: { in: types.keys }

  paginates_per 3

  def self.list_of_operations(user = 0)
    Operation.where(user_id: user).order(created_at: :desc)
  end

  def self.operations_types
    Operation.types.keys.map { |type| [type.humanize, type] }
  end

  def self.model_report_by_category(user, start_date, end_date, type_operations)
    Operation
      .joins(:category)
      .where(user_id: user, odate: start_date..end_date, types: type_operations)
      .group('categories.name')
      .sum(:amount)
  end

  def self.model_report_by_dates(user, start_date, end_date, category_id)
    Operation
      .where(user_id: user, odate: start_date..end_date, category_id:)
      .group(:odate)
      .sum(:amount)
  end
end

app/models/user.rb
# class User
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories, dependent: :destroy
  has_many :operations, dependent: :destroy

  validates :email, uniqueness: true, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
# class CategoriesController 
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_category, only: %i[show edit update destroy]
  before_action :categories_types_set, only: %i[new edit create update]

  def index
    @categories = if user_signed_in?
                    fetch_categories_for_user(current_user.id, params[:page])
                  else
                    fetch_categories(params[:page])
                  end
  end

  def show; end

  def new
    @category = current_user.categories.new
  end

  def edit; end

  def create
    @category = current_user.categories.new(category_params)

    if @category.save
      redirect_to category_url(@category), notice: 'Category was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @category.update(category_params)
      redirect_to category_url(@category), notice: 'Category was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_url, notice: 'Category was successfully destroyed.'
  end

  private

  def fetch_categories_for_user(user_id, page)
    store_current_page(page)
    Category.categories_of_user(user_id).page(current_page)
  end

  def fetch_categories(page)
    store_current_page(page)
    Category.categories_of_user.page(current_page)
  end

  def store_current_page(page)
    session[:current_page] = page if page.present?
  end

  def current_page
    session[:current_page] || 1
  end

  def set_category
    @category = current_user.categories.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to categories_path, alert: 'Record not found'
  end

  def category_params
    params.require(:category).permit(:name, :description, :types)
  end

  def categories_types_set
    @types = Category.categories_types
  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index; end
end

app/controllers/operations_controller.rb
# class of OperationController
class OperationsController < ApplicationController
  before_action :authenticate_user!, except: %i[index]
  before_action :set_operation, only: %i[show edit update destroy]
  before_action :categories_array, :operations_types_set, only: %i[index new show edit create update]

  def index
    @operations = if user_signed_in?
                    fetch_operations_for_user(current_user.id, params[:page])
                  else
                    fetch_operations(params[:page])
                  end
  end

  def show; end

  def new
    @operation = current_user.operations.new(amount: 0, odate: Time.now)
  end

  def edit; end

  def create
    @operation = current_user.operations.new(operation_params)

    if @operation.save
      redirect_to operation_url(@operation), notice: 'Operation was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @operation.update(operation_params)
      redirect_to operation_url(@operation), notice: 'Operation was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @operation.destroy
    redirect_to operations_url, notice: 'Operation was successfully destroyed'
  end

  private

  def fetch_operations(page)
    store_current_page(page)
    Operation.list_of_operations.page(current_page)
  end

  def fetch_operations_for_user(user_id, page)
    store_current_page(page)
    Operation.list_of_operations(user_id).page(current_page)
  end

  def store_current_page(page)
    session[:current_page] = page if page.present?
  end

  def current_page
    session[:current_page] || 1
  end

  def operations_types_set
    @types = Operation.operations_types
  end

  def categories_array
    @categories_array = Category.categories_of_user(current_user.id).pluck(:name, :id) if user_signed_in?
  end

  def set_operation
    @operation = current_user.operations.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to operations_url, alert: 'Operation not found'
  end

  def operation_params
    params.require(:operation).permit(:amount, :odate, :description, :category_id, :types)
  end
end

app/controllers/reports_controller.rb
# class ReportsController
class ReportsController < ApplicationController
  before_action :authenticate_user!, only: %i[index]

  def index; end

  def report_by_category
    @categories_and_amount = Operation.model_report_by_category(
      current_user.id,
      params[:start_date],
      params[:end_date],
      params[:type_operations]
    )

    @amounts = @categories_and_amount.values

    @category_names = @categories_and_amount.keys
  end

  def report_by_dates
    @dates_and_amounts = Operation.model_report_by_dates(
      current_user.id,
      params[:start_date],
      params[:end_date],
      params[:category_id]
    )

    @dates = @dates_and_amounts.keys.map { |date| date.to_date.to_s }

    @amounts = @dates_and_amounts.values.map { |amount| amount }
  end

end

app/helpers/application_helper.rb
# module ApplicationHelper
module ApplicationHelper
  def flash_class(level)
    case level
      when 'notice' then "alert alert-info"
      when 'success' then "alert alert-success"
      when 'error' then "alert alert-danger"
      when 'alert' then "alert alert-warning"
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/categories/_category.html.erb
<div class="mt-3" id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

  <p>
    <strong>Type of Category:</strong>
    <%= category.types.humanize %>
  </p>

</div>

app/views/categories/_form.html.erb
<div class='container mt-4'>
  <div class='col-4 offset-3 w-50'>
    <%= form_with(model: category) do |form| %>
      <% if category.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

          <ul>
            <% category.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="mw-25">
        <div class="mb-3">
          <%= form.label :name, style: "display: block" %>
          <%= form.text_field :name %>
        </div>

        <div class="mb-4">
          <%= form.label :description, style: "display: block" %>
          <%= form.text_field :description %>
        </div>

        <div class="mb-4">
          <%= form.label :category_type, style: "display: inline-block" %>
          <%= form.select(:types, @types) %>
        </div>

        <div>
          <%= form.submit %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/edit.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <h1 class="text-center m-3 p-4">Editing category</h1>
  <div class="d-flex justify-content-center mb-3">
    <%= render "form", category: @category %>
  </div>
  <br>
  <div class="text-center">
    <button class="btn btn-info mb-2 me-2">
      <%= link_to "Back to categories", categories_path %>
    </button>
    <button class="btn btn-success mb-2 me-2">
      <%= link_to "Show this category", @category %>
    </button>
  </div>
</div>

app/views/categories/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container d-flex flex-column p-3">
  <h1 class="text-center">Categories</h1>
  <div class="new_category_link mb-2 pb-3 text-center">
    <button class="btn btn-success">
      <%= link_to "Add new category", new_category_path(page: params[:page]) %>
    </button>
  </div>

  <div class="mb-3" id="categories">
    <% @categories.each do |category| %>
      <%= render category %>
      <p>
        <button class="btn btn-success">
          <%= link_to "Show this category", category_path(category, page: params[:page]) %>
        </button>
      </p>
      <div></div>
    <% end %>
  </div>

  <div class="paginate">
    <%= paginate @categories%>
  </div>
</div>

app/views/categories/new.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <h1 class="text-center m-3 p-4">New category</h1>
  <div class="d-flex justify-content-center mb-3">
    <%= render "form", category: @category %>
  </div>
  <div class="text-center">
    <button class="btn btn-info mt-3 me-2">
      <%= link_to "Back to categories", categories_path(page: params[:page]) %>
    </button>
  </div>
</div>

app/views/categories/show.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <p style="color: green"><%= notice %></p>
  <h1 class="text-center pt-3">About category</h1>
  <div class="d-flex justify-content-center">
    <%= render @category %>
  </div>
  <div class="text-center pt-3">
    <button class="btn btn-info mb-2 me-2"> 
      <%= link_to "Back to categories", categories_path(page: params[:page]) %>
    </button>
    <button class="btn btn-success mb-2 me-2">
      <%= link_to "Edit this category", edit_category_path(@category) %>
    </button>
    <button class="btn btn-danger mb-2 me-2">
      <%= link_to "Destroy this category", category_path(@category), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    </button>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CASH_COMMANDER</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <%= javascript_importmap_tags %>

  </head>

  <body>
    <header>
      <%= render 'shared/header' %>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer>
      <%= render 'shared/footer' %>
    </footer>
  </body>
</html>

app/views/main/index.html.erb
<main class="container h-75 text-center">
  <h1>Manage Your Finances with Cash_Commander</h1>
  <div class="text-start mt-4">
    <span><strong>OUR MISSION: </strong></span>
    <p>To help users manage their finances, save money, and achieve financial stability.</p>
  </div>
  <div class="text-start mt-4">
    <span><strong>OUR GOAL: </strong></span>
    <p>To develop an intuitive and user-friendly web application that allows users to keep records of their income and expenses, control their finances, and plan for the future. Our application will assist users in understanding where their money is going, making informed financial decisions, and ensuring financial stability.</p>
  </div>
</main>

app/views/operations/_form.html.erb
<div class='container mt-4'>
  <div class='col-4 offset-3 w-50'>
    <%= form_with(model: operation) do |form| %>
      <% if operation.errors.any? %>
        <div style="color: red">
          <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

          <ul>
            <% operation.errors.each do |error| %>
              <li><%= error.full_message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div>
        <%= form.label :amount, style: "display: block" %>
        <%= form.text_field :amount %>
      </div>

      <div>
        <%= form.label :odate, style: "display: block" %>
        <%= form.datetime_field :odate %>
      </div>

      <div>
        <%= form.label :description, style: "display: block" %>
        <%= form.text_field :description %>
      </div>

      <div class="d-flex mt-3">
        <div class="w-50">
          <%= form.label :categories %>
          <%= form.select(:category_id, @categories_array) %>
        </div>

        <div class="w-50">
          <%= form.label :types_of_operation %>
          <%= form.select(:types, @types) %>
        </div>
      </div>

      <div class="mt-3">
        <%= form.submit %>
      </div>
    <% end %>
  </div>
</div>

app/views/operations/_operation.html.erb
<div class="mt-3" id="<%= dom_id operation %>">
  <p>
    <strong>Amount:</strong>
    <%= operation.amount %>
  </p>

  <p>
    <strong>Odate:</strong>
    <%= operation.odate %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= operation.description %>
  </p>

  <p>
    <strong>Category:</strong>
    <% h = categories_array.to_h { |v| [v[1], v[0]] } %>
    <%= h[operation.category_id] %>
  </p>

  <p>
    <strong>Types of operations:</strong>
    <%= operation.types.humanize %>
  </p>

</div>

app/views/operations/edit.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <h1 class="text-center m-3 p-4">Editing operation</h1>
  <div class="d-flex justify-content-center mb-3">
    <%= render "form", operation: @operation %>
  </div>
  <br>
  <div class="text-center">
    <button class="btn btn-info mb-2 me-2">
      <%= link_to "Back to operations", operations_path %>
    </button>
    <button class="btn btn-success mb-2 me-2"> 
      <%= link_to "Show this operation", @operation %>
    </button> 
  </div>
</div>

app/views/operations/index.html.erb
<p style="color: green"><%= notice %></p>
<div class="container d-flex flex-column p-3">
  <h1 class="text-center">Operations</h1>
  <div class="new_operation_link mb-2 pb-3 text-center">
    <button class="btn btn-success">
      <%= link_to "Add new operation", new_operation_path(page: params[:page]) %>
    </button>
  </div>
  <div class="mb-3" id="operations">
    <% @operations.each do |operation| %>
      <%= render operation, categories_array: @categories_array %>
      <p>
        <button class="btn btn-success">
          <%= link_to "Show this operation", operation_path(operation, page: params[:page]) %>
        </button>
      </p>
      <div></div>
    <% end %>
  </div>

  <div class="paginate">
    <%= paginate @operations %>
  </div>
</div>

app/views/operations/new.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <h1 class="text-center m-3 p-4">New operation</h1>
  <div class="d-flex justify-content-center mb-3">
    <%= render "form", operation: @operation %>
  </div>
  <div class="text-center">
    <button class="btn btn-info mt-3 me-2">
      <%= link_to "Back to operations", operations_path(page: params[:page]) %>
    </button>
  </div>
</div>

app/views/operations/show.html.erb
<div class="container h-75 me-auto d-flex flex-column justify-content-start">
  <p style="color: green"><%= notice %></p>
  <h1 class="text-center m-3 p-4">About operation</h1>
  <div class="d-flex justify-content-center">
    <%= render partial: 'operation', locals: {
      operation: @operation, categories_array: @categories_array
    } %>
  </div>
  <div class="text-center pt-3">
    <button class="btn btn-info mb-2 me-2"> 
      <%= link_to "Back to operations", operations_path(page: params[:page]) %>
    </button>
    <button class="btn btn-success mb-2 me-2">
      <%= link_to "Edit this operation", edit_operation_path(@operation) %>
    </button>
    <button class="btn btn-danger mb-2 me-2">
      <%= link_to "Destroy this operation", operation_path(@operation), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} %>
    </button>
  </div>
</div>

app/views/reports/_chart.html.erb
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
<script type='text/javascript'>
  (function(){
    if(!sessionStorage.getItem('firstLoad')){
      sessionStorage['firstLoad'] = true;
      window.location.reload();
    }else{
      sessionStorage.removeItem('firstLoad');
  }})();
</script>

app/views/reports/index.html.erb
<div class='container mt-4'>
  <div class='col-4 offset-3 w-50'>
    <h1 class="text-center m-3 p-4">Reports generator</h1>

    <div class="d-flex justify-content-center w-100">
      <%= form_with url: "", method: :get do |form| %>
        <div class="mt-3">
          <strong><%= form.label :start_date, "Date YYYY-MM-DD" %></strong>
          <%= form.datetime_field :start_date, value: Date.today.beginning_of_month.strftime("%Y-%m-%dT%H:%M") %>
        </div>
        <div class="mt-3">
          <strong><%= form.label :end_date, "Date YYYY-MM-DD" %></strong>
          <%= form.datetime_field :end_date, value: Date.today.end_of_month.strftime("%Y-%m-%dT%H:%M") %>
        </div>
        <div class="mt-3">
          <strong><%= form.label :"Type of operation" %></strong>
          <% types_of_operation = [["Expenses", 2], ["Income", 1]] %>
          <%= form.select(:type_operations, types_of_operation) %>
        </div>
        <div class="mt-3">
          <strong><%= form.label :category_id, "Category" %></strong>
          <%= form.collection_select :category_id, Category.order(:name), :id, :name %>
        </div>
        <div class="text-center mt-3 p-4">
          <button type="reset" class="btn btn-danger mb-2 me-2" id="btn_reset" name="btn_reset">Reset</button>
          <button type="submit" class="btn btn-success mb-2 me-2" id="btn_dates" formaction="report_by_dates">By dates</button>
          <button type="submit" class="btn btn-primary mb-2 me-2" id="btn_graph" formaction="report_by_category">Chart</button>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/report_by_category.html.erb
<div class="mb-3">
  <%= render template: 'reports/index' %>
</div>

<div class="container-fluid">
  <div class="text-center mt-3">
    <h1>Report for the period: <%= params[:start_date] %> - <%= params[:end_date] %> </h1>
  </div>
  <div class="container bg-body-secondary d-flex justify-content-evenly">
    <div class="p-4">
      <%= render 'chart' %>
      
      <h4 class="text-center">Chart in section of categories</h4>
      <div class="chart_by_categories w-100">
        <canvas class="canvas" id="myChart"></canvas>
        <script>
        const ctx = document.getElementById('myChart');
        const data = {
        labels: <%= raw @category_names %>,
        datasets: [{
            label: "Total amount by category",
            data: <%= @amounts %>,
            backgroundColor: [
            'rgb(255, 99, 132)',
            'rgb(54, 162, 235)',
            'rgb(255, 205, 86)',
            'rgb(0, 255, 0)',
            'rgb(255, 51, 153)',
            'rgb(255, 128, 0)',
            'rgb(51, 51, 255)',
            'rgb(255, 255, 51)',
            'rgb(255, 51, 255)',
            'rgb(246, 20, 50)'
            ],
            hoverOffset: 10
        }]
        };;

        const config = {
        type: 'pie',
        data: data,
        options: {
          responsive: false
        }
        };

        const myChart = new Chart(ctx, config);
        </script>
      </div>
    </div>

    <div class="p-4 table-responsive">
      <h4 class="text-center">Table in section of categories</h4>
      <table class="table table-success table-hover table-bordered border-1">
        <thead>
          <tr>
            <th>Category</th>
            <th>Amount</th>
          </tr> 
        </thead>
        <tbody class="table-group-divider">
          <% @categories_and_amount.each do |category_item, amount_item| %>
          <tr>
            <td ><%= category_item %></td>
            <td><%= amount_item.round(2) %></td>
          </tr>
          <% end %>
        </tbody>
        <tfoot class="table-group-divider">
          <tr>
            <td><strong>Result: </strong></td>
            <td><strong><%= @amounts.sum.round(2) %></strong></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/reports/report_by_dates.html.erb
<div class="mb-3">
  <%= render template: 'reports/index' %>
</div>

<div class="container-fluid">
  <div class="text-center mt-3">
    <h1>Report for the period: <%= params[:start_date] %> - <%= params[:end_date] %> </h1>
  </div>
  <div class="container bg-body-secondary d-flex justify-content-evenly">
    <div class="p-4">
      <%= render 'chart' %>
      
      <h4 class="text-center">Expenses by category by date</h4>
      <div class="Chart_by_categories w-100">
        <canvas class="canvas" id="myChart"></canvas>
        <script>
        const ctx = document.getElementById('myChart');
        const data = {
        labels: <%= raw @dates %>,
        datasets: [{
          label: 'Expenses by day',
          data: <%= @amounts %>,
          fill: false,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
          }]
        };

        const config = {
          type: 'line',
          data: data,
          options: {
            responsive: false
          }
        };
        const myChart = new Chart(ctx, config);
        </script>
      </div>
    </div>

    <div class="p-4 table-responsive">
      <h4 class="text-center">The table of costs by date</h4>
      <table class="table table-success table-hover table-bordered border-1">
        <thead>
          <tr>
            <th>Дата</th>
            <th>Сума</th>
          </tr>
        </thead>
        <tbody class="table-group-divider">
          <% @dates_and_amounts.each do |dates_item, amount_item| %>
          <tr>
            <td><%= dates_item.to_date %></td>
            <td><%= amount_item.round(2) %></td>
          </tr>
          <% end %>
        </tbody>
        <tfoot class="table-group-divider">
          <tr>
            <td><strong>Result: </strong></td>
            <td><strong><%= @amounts.sum.round(2) %></strong></td>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="mt-3">
    <nav class="nav justify-content-center m-auto">
      <div class="text-center p-1 w-50 fs-5 ">
        <i class="bi bi-github"></i><a class="footer-link-item me-1" href="https://github.com/Khval-Andrii" alt="github link"> github</a>
        <a class="footer-link-item me-1" href="https://www.codewars.com/users/Khval-Andrii" alt="codewars link"><img src="https://www.codewars.com/users/Khval-Andrii/badges/small"></a>
        <i class="bi bi-linkedin"></i><a class="footer-link-item me-1" href="https://www.linkedin.com/in/khval-andrii-b81689151/" alt="linkedin link"> linkedin</a>
      </div>
    </nav>
  </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg bg-success" data-bs-theme="dark">
  <!-- Navbar content -->
  <div class="container justify-content-between">
    <a class="navbar-brand" href="<%= "/main/index" %>"><strong><i class="bi bi-cash-coin"></i> CASH_COMMANDER</strong></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-center" id="navbarSupportedContent">
      <ul class="navbar-nav nav-pills justify-content-around">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="<%= categories_path %>">Categories</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= operations_path %>">Operations</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= reports_index_path %>">Reports</a>
        </li>
      </ul>
    </div>
    <div class="col-md-3 text-end">
          <% if !user_signed_in? %>
            <%= link_to new_user_session_path do %>
              <button type="button" class="btn btn-outline-warning me-2">Login</button>
            <% end %>
            <%= link_to new_user_registration_path do %>
              <button type="button" class="btn btn-warning">Sign-up</button>
            <% end %>
          <% else %>
            <%= link_to edit_user_registration_path do %>
              <button type="button" class="btn btn-outline-warning me-2">Edit</button>
            <% end %>
            <%= link_to destroy_user_session_path, data: { turbo_method: :delete  } do %>
                <button type="button" class="btn btn-warning">Sign-out</button>
            <% end %>
          <% end %>
        </div>
  </div>
</nav>